# Generated by Django 4.2.1 on 2023-05-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option_A', models.CharField(max_length=100)),
                ('option_B', models.CharField(max_length=100)),
                ('option_C', models.CharField(max_length=100)),
                ('option_A_count', models.IntegerField(default=0)),
                ('option_B_count', models.IntegerField(default=0)),
                ('option_C_count', models.IntegerField(default=0)),
            ],
        ),
    ]
